name: LeagueOfMinecraft
main: me.bittnerdenaro.lom.LeagueOfMinecraft
version: 1.0
commands:
  create-turret:
    description: creates a turret
    usage: /create-turret
  slow:
    descript: causes the slow CC
    usage: /slow <percent> <duration in ticks>